spring.application.name=notification-system
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/notifications}
spring.datasource.username=${DB_USER:notif}
spring.datasource.password=${DB_PASSWORD:notif}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
